MonitoringPrice.Web/Areas/Admin/Controllers/ManufacturerController.cs
using Microsoft.AspNetCore.Mvc;
using MonitoringPrice.Services.Interfaces;
using MonitoringPrice.Services.Models;

namespace MonitoringPrice.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ManufacturerController : Controller
    {
        private readonly IManufacturerService _manufacturerService;

        public ManufacturerController(IManufacturerService manufacturerService)
        {
            _manufacturerService = manufacturerService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<ManufacturerModel> bbb = await _manufacturerService.GetAllManufacturerFromApi();
            return View(bbb);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = id == default ? new ManufacturerModel() : await _manufacturerService.GetManufactyrerById(id);
            return View(model);
        }

        public async Task<ActionResult> Save(ManufacturerModel manufacturer)
        {
            if (ModelState.IsValid)
            {
                await _manufacturerService.Save(manufacturer);
            }
            return View(manufacturer);
        }
    }
}

MonitoringPrice.Web/Areas/Admin/Views/Manufacturer/Edit.cshtml
@model MonitoringPrice.Services.Models.ManufacturerModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;
}


<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="Manufacturer" asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input asp-for="ManufacturerName" class="form-control" />
                <span asp-validation-for="ManufacturerName" class="text-danger"></span>
            </div>

            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>

MonitoringPrice.Web/Areas/Admin/Views/Manufacturer/Index.cshtml
@model IEnumerable<ManufacturerModel>
<h3>Справочник производителей</h3>
<div class="div-box">
    <a asp-area="Admin" asp-controller="Manufacturer" asp-action="Edit" asp-route-id="">Добавить производителя</a>
</div>

<div>
    <div>
        @if (Model.Any())
        {
            <div>
                @foreach (ManufacturerModel item in Model)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="Manufacturer" asp-action="Edit" asp-route-id="@item.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@item.Id" asp-area="Admin" asp-controller="Manufacturer" asp-action="Delete" asp-route-id="@item.Id" method="post">
                            <input type="hidden" name="id" value="@item.Id">
                            <a href="#" onclick="document.getElementById('form-@item.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Manufacturer" asp-action="Index" asp-route-id="@item.Id">
                            @($"{item.ManufacturerName}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>
</div>