MonitoringPrice.Web/Models/ProductViewModel.cs
using MonitoringPrice.Services.Models;

namespace MonitoringPrice.Web.Models
{
    public class ProductViewModel
    {
        public IEnumerable<CategoryModel> CategoryModels { get; set; }
        public IEnumerable<ManufacturerModel> ManufacturerModels { get; set; }
        public IEnumerable<ProductModel> ProductModels { get; set; }
    }
}

MonitoringPrice.Web/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using MonitoringPrice.Services.Interfaces;
using MonitoringPrice.Services.Models;

namespace MonitoringPrice.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<CategoryModel> bbb = await _categoryService.GetAllCategoryFromApi();
            return View(bbb);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var model = id == default ? new CategoryModel() : await _categoryService.GetCategoryById(id);
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Save(CategoryModel manufacturer)
        {
            if (ModelState.IsValid)
            {
                await _categoryService.SaveCategory(manufacturer);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<ActionResult> Delete(int id)
        {
            await _categoryService.DeleteCategory(id);
            return RedirectToAction("Index");
        }
    }
}

MonitoringPrice.Web/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MonitoringPrice.Services.Interfaces;
using MonitoringPrice.Services.Models;
using MonitoringPrice.Web.Models;

namespace MonitoringPrice.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IManufacturerService _manufacturerService;
        private readonly ICategoryService _categoryService;
        public ProductController(IProductService productService, IManufacturerService manufacturerService, ICategoryService categoryService)
        {
            _productService = productService;
            _manufacturerService = manufacturerService;
            _categoryService = categoryService;
        }

        // GET: ProductController
        public async Task<IActionResult> Index()
        {
            ViewBag.Manufacturer = await _manufacturerService.GetAllManufacturerFromApi();
            ViewBag.Categories = await _categoryService.GetAllCategoryFromApi();

            var Product = await _productService.GetAllProduct();
            return View(Product);
        }


        // GET: ProductController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.Manufacturer = await _manufacturerService.GetAllManufacturerFromApi();
            ViewBag.Categories = await _categoryService.GetAllCategoryFromApi();

            var model = new ProductModel();

            if (id != 0)
            {
                model = await _productService.GetProductById(id);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Save(ProductModel editModel)
        {
            if (ModelState.IsValid)
            {
                var categoryValue = Request.Form.FirstOrDefault(x => x.Key == "categoryId").Value;
                int.TryParse(categoryValue, out int categoryInt);

                if (categoryInt != 0)
                { 
                    var manufacturerValue = Request.Form.FirstOrDefault(x => x.Key == "manufacturerId").Value;
                    int.TryParse(manufacturerValue, out int manufactureInt);

                    if (manufactureInt != 0)
                    {
                        editModel.ManufacturerId = manufactureInt;
                        editModel.CategoryId = categoryInt;
                        await _productService.Save(editModel);
                    }
                }
            }
            return RedirectToAction("Index");
        }





        // GET: ProductController/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

    }
}

MonitoringPrice.Web/Areas/Admin/Views/Product/Edit.cshtml
@model ProductModel

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    string strTitle = "Редактировать запись";
    ViewBag.Title = strTitle;

    var manufacturers = (List<ManufacturerModel>)ViewBag.Manufacturer;
    var category = (List<CategoryModel>)ViewBag.Categories;
}



<div>
    <h2>@strTitle</h2>
    <form class="form-check-inline" asp-area="Admin" asp-controller="Product" asp-action="Save" method="post" enctype="multipart/form-data">
        <label>Категория :</label>

        <select name="CategoryId">
            @if (category.Any())
            {
                @foreach (var item in category)
                {
                    <option value="@item.Id">@item.CategoryName</option>
                }
            }
        </select>

        <lablel>Производитель : </lablel>
        <select name="ManufacturerId">
            @if (manufacturers.Any())
            {
                @foreach (var item in manufacturers)
                {
                    <option value="@item.Id">@item.ManufacturerName</option>
                }
            }

        </select>
    <div>
            <div asp-validation-summary="All"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>

            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Назад</a>
</div>

MonitoringPrice.Web/Areas/Admin/Views/Product/Index.cshtml
@model IEnumerable<ProductModel>
@{
    var manufacturers = (List<ManufacturerModel>)ViewBag.Manufacturer;
    var category = (List<CategoryModel>)ViewBag.Categories;
}

<h3>Перечень продуктов</h3>
<div class="div-box">
    <a asp-area="Admin" asp-controller="Product" asp-action="Edit" asp-route-id="">Добавить продукт</a>
</div>

<form class="form-check-inline">
    <label>Категория :</label>
    <select name="categoryId">
        @if (category.Any())
        {
            @foreach (var item in category)
            {
                <option value="@item.Id">@item.CategoryName</option>
            }
        }
    </select>

    <lablel>Производитель : </lablel>
    <select name="manufacturerId">
        @if (Model.Any())
        {
            @foreach (var item in manufacturers)
            {
                <option value="@item.Id">@item.ManufacturerName</option>
            }
        }

    </select>
</form>

<div>
    @if (Model.Any())
    {
        <div>
            @foreach (ProductModel item in Model)
            {
                <div>
                    <a asp-area="Admin" asp-controller="Product" asp-action="Edit" asp-route-id="@item.Id">редактировать</a>
                    |
                    <form style="display: inline-block;" id="form-@item.Id" asp-area="Admin" asp-controller="Category" asp-action="Delete" asp-route-id="@item.Id" method="post">
                        <input type="hidden" name="id" value="@item.Id">
                        <a href="#" onclick="document.getElementById('form-@item.Id').submit();">удалить</a>
                    </form>
                    |
                    <a asp-area="" asp-controller="Product" asp-action="Index" asp-route-id="@item.Id">
                        @($"{item.ProductName}")
                    </a>
                </div>
            }
        </div>
    }
</div>